export const team = [
	{
		name: 'Mayfa Shadrina Siddi ',
		url: '/characters/mayfa.shadrina',
		house: 'Apocalypse',
		role: 'UI/UX',
		image: '/assets/mayfa.svg',
	},
	{
		name: 'Nur Fajar Sayyidul Ayyam',
		url: '/characters/nur.fajar11',
		house: 'Horror',
		role: 'UI/UX',
		image: '/assets/fajar.svg',
	},
	{
		name: 'Naila Azizah',
		url: '/characters/naila.azizah',
		house: 'Comedy',
		role: 'UI/UX',
		image: '/assets/naila.svg',
	},
	{
		name: 'Muhammad Akmal Hakim',
		url: '/characters/muhammad.akmal14',
		house: 'Animation',
		role: 'UI/UX',
		image: '/assets/akmal.svg',
	},
	{
		name: 'Adjie Djaka Permana',
		url: '/characters/adjie.djaka',
		house: 'Superhero',
		role: 'Front-end Developer',
		image: '/assets/adjie.svg',
	},
	{
		name: 'Eduardus Tjitrahardja',
		url: '/characters/eduardus.tjitrahardja',
		house: 'Space',
		role: 'Front-end Developer',
		image: '/assets/edu.svg',
	},
	{
		name: 'Nayyara Airlangga Raharjo',
		url: '/characters/nayyara.airlangga',
		house: 'Action',
		role: 'Front-end Developer',
		image: '/assets/angga.svg',
	},
	{
		name: 'Muhammad Hilman Al Ayubi',
		url: '/characters/muhammad.hilman11',
		house: 'Action',
		role: 'Front-end Developer',
		image: '/assets/bee.svg',
	},
	{
		name: 'Rendy Arya Kemal',
		url: '/characters/rendy.arya',
		house: 'Action',
		role: 'Back-end Developer',
		image: '/assets/rendy.svg',
	},
	{
		name: 'Mohammad Ferry Husnil Arif',
		url: '/characters/mohammad.ferry',
		house: 'Comedy',
		role: 'Back-end Developer',
		image: 'https://ka-devel.rorre.xyz/assets/student/9xapcqhpx3hxx3o0.jpg',
	},
	{
		name: 'Ahmadhi Prananta Hastiputra',
		url: '/characters/ahmadhi.prananta',
		house: 'Horror',
		role: 'Back-end Developer',
		image: '/assets/ahmadhi.svg',
	},
	{
		name: 'Naufal Weise Widyatama',
		url: '/characters/naufal.weise',
		house: 'Horror',
		role: 'Back-end Developer',
		image: 'https://ka-devel.rorre.xyz/assets/student/ci9ty5nn6hyfb3ds.jpg',
	},
]
